### ISSUE TITLE
Issue when using brackets in pure string values

### ISSUE THREAD

**Issue by MichaelJJ** [skalahonza/InfHelper#11]
Hello,

We've noticed that if there is either a `[` or `]` character in a quoted string value, we get an exception when parsing.

Should the characters be added to the ignored category here: https://github.com/skalahonza/InfHelper/blob/master/InfHelper/src/Parsers/ContentParser.cs#L157

**Comment by skalahonza** [comment]
hello, can you please provide a sample of some inf file that has this problem?

**Comment by nikolausmoll** [comment]
Why do you need an example? The reason is obvious, because the brackets aren't handled as Letters when parsing a value, they have the "wrong" TokenTypes: CategoryOpening and CategoryClosing

So, these Token Types have to be valid Token Types when reading a quotes string.

**Comment by nikolausmoll** [comment]
Change InitPureValueParsing and add

                new CategoryOpeningToken(),
                new CategoryClosingToken(),

Change ValidTokenFoundDuringPureValueParsing and change the first case to:

                case TokenType.Letter:
                case TokenType.ValueSeparator:
                case TokenType.WhiteSpace:
                case TokenType.Space:
                case TokenType.CategoryOpening:
                case TokenType.CategoryClosing:
                    keyTmpValue += tokenBase.Symbol;
                    break;

Change the Unit Test to:

        [TestMethod()]
        public void PureValueParsingTest()
        {
            string formula =
                "[DestinationDirs]\r\n" + 
                "Razer_CoInstaller_CopyFiles = 11\r\n" +
                "Razer_Installer_CopyFiles = 16422,\"Razer\\RzWizardPkg\"\r\n" +
                "Razer_Installer_CopyFilesWOW64 = 16426,\"Razer\\RzWizardPkg\"\r\n" +
                "Razer_Installer_CopyFilesWithBrackets = 16428,\"Razer\\RzWizardPkg [Brackets]\"";
            var helper = new InfUtil();
            var data = helper.Parse(formula);
            Assert.AreEqual("11", data["DestinationDirs"]["Razer_CoInstaller_CopyFiles"].PrimitiveValue);
            Assert.AreEqual("16422, \"Razer\\RzWizardPkg\"", data["DestinationDirs"]["Razer_Installer_CopyFiles"].PrimitiveValue);
            Assert.AreEqual("16426, \"Razer\\RzWizardPkg\"", data["DestinationDirs"]["Razer_Installer_CopyFilesWOW64"].PrimitiveValue);
            Assert.AreEqual("16428, \"Razer\\RzWizardPkg [Brackets]\"", data["DestinationDirs"]["Razer_Installer_CopyFilesWithBrackets"].PrimitiveValue);
        }

       
I updated my pull request with the fix for comments in the values sections

**Comment by MichaelJJ** [comment]
> hello, can you please provide a sample of some inf file that has this problem?

You can replicate it by adding brackets to quoted a string field in any of the test INFs, for example:

https://github.com/skalahonza/InfHelper/blob/master/InfHelperTests/infs/oem12.inf

```
[Strings]
SPSVCINST_ASSOCSERVICE= 0x00000002
MfgName="NVI[D]IA"
DiskId1 = "NVVHCI Driver Disk"
DeviceDesc = "NVVHCI Enumerator"
ServiceDesc = "NVVHCI Enumerator Service"
```

It seems that either the solution from the previous comment, or adding the brackets to the ignored section work, I am not sure what option is better.

**Comment by nikolausmoll** [comment]
You are right, ignoring them seems to be enough.
I update my PR

**Comment by MichaelJJ** [comment]
> You are right, ignoring them seems to be enough. I update my PR

Yeah, I did a small test and noticed it worked, I wasn't sure that was the best option. I figured filing a ticket to get a more detailed look would be best.

**Comment by nikolausmoll** [comment]
To me, it looks more reasonable to ignore these tokens than to pretend to support tokens for category start/end within value parsing. This variant (ignoring) requires less thinking.

**Comment by MichaelJJ** [comment]
Hello, any update on this, should this be resolved in the latest release?

**Comment by MichaelJJ** [comment]
Appears to be fixed in latest release
