### ISSUE TITLE
Encoding issue

### ISSUE THREAD

**Issue by masonticehurst** [skalahonza/InfHelper#4]
Hi! I am currently using your software to parse several .inf driver files and it works fairly flawlessly.

One issue I'm facing is when parsing files with characters from other languages. For example this file seems to include Japanese and Chinese characters:

https://hastebin.com/uvetuzupag.inf

On lines 2826 and below some characters are interpreted as the '[' symbol which causes parsing to fail (even though the file's encoding is UTF-8). Is there anyway around this and is there something I have to change or something that your software can work around?

Thanks

**Comment by skalahonza** [comment]
Hi. Sorry for the long response it has been a long time since I created this project. Is the issue still relevant? If so, can you please resubmit the hastebin?
