### ISSUE TITLE
Whitespaces in category break the parser

### ISSUE THREAD

**Issue by PietroConvalleAD** [skalahonza/InfHelper#6]
Code used:
```
var helper = new InfUtil();
helper.ParseFile(path);
```

I get this error:
```
InfHelper.Exceptions.InvalidTokenException: 'Invalid tokenBase found during category parsing parsing: 
Symbol:  
Token type: WhiteSpace
Allowed tokens: CategoryClosing, Letter
```

[infifle.txt](https://github.com/skalahonza/InfHelper/files/10381861/infifle.txt)

**Comment by skalahonza** [comment]
it seems that category
`[OEM URLS]` contains whitespace
long time since I have done this project, so I will need to check if that is valid and if yes, then adjust the parser

**Comment by skalahonza** [comment]
If I get ti right
according to: https://learn.microsoft.com/en-us/windows-hardware/drivers/install/general-syntax-rules-for-inf-files#-section-names

it seems that that space is not forbidden

**Comment by PietroConvalleAD** [comment]
I think so, that's an official driver from "Brother"

**Comment by skalahonza** [comment]
ok, I will try to patch it soon

**Comment by skalahonza** [comment]
ok, so I added the file you provided into tests
I also added a test to ensure that category name is parsed correctly (with space)
please verify that it works in the new version of nuget
https://www.nuget.org/packages/InfHelper/0.7.1
